spring:
  application:
    name: ElectorAI
  datasource:
    url: jdbc:h2:tcp://localhost//Users/lingfeng/Desktop/zhiyunti/backend/SQL/H2elevator;MODE=MySQL;DATABASE_TO_LOWER=TRUE;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1;FILE_LOCK=FS
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console

  sql:
    init:
      mode: never
      schema-locations: classpath:SQL/fix_sequence.sql,classpath:SQL/h2_data_import.sql

  ai:
    openai:
      api-key: sk-be78f7e5e1f74f478d49a6636aa2b3ea
      base-url: https://api.deepseek.com
      chat:
        options:
          model: deepseek-chat
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java
      exclude: static/**,public/**,templates/**,log/**
  jackson:
    property-naming-strategy: SNAKE_CASE

server:
  port: 8080

mybatis-plus:
  type-handlers-package: com.example.V1.Handler
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      id-type: AUTO
  mapper-locations: classpath*:mapper/*.xml

